/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.AddQuestion;

import Controller.listagem_de_perguntas;

import java.sql.SQLException;

/**
 *
 * @author vasco
 */
public class RespostaCorrespondencia extends javax.swing.JFrame {

    /**
     * Creates new form RespostaCorrespondencia
     */
    public RespostaCorrespondencia(String subject, String topic) {
        initComponents(subject, topic);
        setDefaultCloseOperation(RespostaCorrespondencia.DISPOSE_ON_CLOSE);
    }

    public RespostaCorrespondencia() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String subject, String topic) {

        jLabelOpcao1 = new javax.swing.JLabel();
        jLabelOpcao2 = new javax.swing.JLabel();
        jLabelOpcao3 = new javax.swing.JLabel();
        jLabelOpcao4 = new javax.swing.JLabel();
        jTextFieldOpcao1 = new javax.swing.JTextField();
        jTextFieldOpcao3 = new javax.swing.JTextField();
        jTextFieldOpcao2 = new javax.swing.JTextField();
        jTextFieldOpcao4 = new javax.swing.JTextField();
        jLabelResposta1 = new javax.swing.JLabel();
        jLabelResposta2 = new javax.swing.JLabel();
        jLabelResposta3 = new javax.swing.JLabel();
        jLabelResposta4 = new javax.swing.JLabel();
        jTextFieldResposta1 = new javax.swing.JTextField();
        jTextFieldResposta2 = new javax.swing.JTextField();
        jTextFieldResposta3 = new javax.swing.JTextField();
        jTextFieldResposta4 = new javax.swing.JTextField();
        botaoSubmeterPerguntaCorrespondencia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelOpcao1.setText("1)");

        jLabelOpcao2.setText("2)");

        jLabelOpcao3.setText("3)");

        jLabelOpcao4.setText("4)");

        jLabelResposta1.setText("1)");

        jLabelResposta2.setText("2)");

        jLabelResposta3.setText("3)");

        jLabelResposta4.setText("4)");

        jTextFieldResposta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldResposta1ActionPerformed(evt);
            }
        });

        botaoSubmeterPerguntaCorrespondencia.setText("Submeter");
        botaoSubmeterPerguntaCorrespondencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (!(jTextArea1.getText().equals("Pergunta") || jTextArea1.getText().equals("") || jTextFieldOpcao1.getText().equals("") || jTextFieldOpcao2.getText().equals("") || jTextFieldOpcao3.getText().equals("") || jTextFieldOpcao4.getText().equals("") || jTextFieldResposta1.getText().equals("") || jTextFieldResposta2.getText().equals("") || jTextFieldResposta3.getText().equals("") || jTextFieldResposta4.getText().equals(""))) {
                    String topicid = null;
                    try {
                        topicid = listagem_de_perguntas.getTopicIdwithSubjectandtopic(subject, topic);
                    } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }

                    String query = String.format("INSERT INTO QUESTION (description, type, topicid) VALUES ('%s', 'Correspondência', '%s');", jTextArea1.getText().toString(), topicid);
                    String id;

                    try {
                        listagem_de_perguntas.addQuestion(query);
                    } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }

                    try {
                        id = listagem_de_perguntas.maxid();
                    } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }

                    try {
                        listagem_de_perguntas.addQuestion(String.format("INSERT INTO MATCHFOLLOWING VALUES ('%s', '%s', %s);", jTextFieldOpcao1.getText(), jTextFieldResposta1.getText(), id));
                    } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }

                    try {
                        listagem_de_perguntas.addQuestion(String.format("INSERT INTO MATCHFOLLOWING VALUES ('%s', '%s', %s);", jTextFieldOpcao2.getText(), jTextFieldResposta2.getText(), id));
                    } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }

                    try {
                        listagem_de_perguntas.addQuestion(String.format("INSERT INTO MATCHFOLLOWING VALUES ('%s', '%s', %s);", jTextFieldOpcao3.getText(), jTextFieldResposta3.getText(), id));
                    } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }

                    try {
                        listagem_de_perguntas.addQuestion(String.format("INSERT INTO MATCHFOLLOWING VALUES ('%s', '%s', %s);", jTextFieldOpcao4.getText(), jTextFieldResposta4.getText(), id));
                    } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }
                    dispose();
                }
            }
            });

                jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Pergunta");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelOpcao4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelOpcao3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelOpcao2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelOpcao1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldOpcao1)
                            .addComponent(jTextFieldOpcao2)
                            .addComponent(jTextFieldOpcao3)
                            .addComponent(jTextFieldOpcao4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelResposta3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldResposta3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelResposta2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldResposta2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelResposta4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldResposta4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelResposta1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldResposta1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(botaoSubmeterPerguntaCorrespondencia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelOpcao1)
                            .addComponent(jTextFieldOpcao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelOpcao2)
                            .addComponent(jTextFieldOpcao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelOpcao3)
                            .addComponent(jTextFieldOpcao3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelOpcao4)
                            .addComponent(jTextFieldOpcao4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelResposta1)
                            .addComponent(jTextFieldResposta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelResposta2)
                            .addComponent(jTextFieldResposta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelResposta3)
                            .addComponent(jTextFieldResposta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelResposta4)
                                    .addComponent(jTextFieldResposta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoSubmeterPerguntaCorrespondencia)
                                .addGap(31, 31, 31))))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldResposta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldResposta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldResposta1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RespostaCorrespondencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RespostaCorrespondencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RespostaCorrespondencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RespostaCorrespondencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RespostaCorrespondencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSubmeterPerguntaCorrespondencia;
    private javax.swing.JLabel jLabelOpcao1;
    private javax.swing.JLabel jLabelOpcao2;
    private javax.swing.JLabel jLabelOpcao3;
    private javax.swing.JLabel jLabelOpcao4;
    private javax.swing.JLabel jLabelResposta1;
    private javax.swing.JLabel jLabelResposta2;
    private javax.swing.JLabel jLabelResposta3;
    private javax.swing.JLabel jLabelResposta4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldOpcao1;
    private javax.swing.JTextField jTextFieldOpcao2;
    private javax.swing.JTextField jTextFieldOpcao3;
    private javax.swing.JTextField jTextFieldOpcao4;
    private javax.swing.JTextField jTextFieldResposta1;
    private javax.swing.JTextField jTextFieldResposta2;
    private javax.swing.JTextField jTextFieldResposta3;
    private javax.swing.JTextField jTextFieldResposta4;
    // End of variables declaration//GEN-END:variables
}
