/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ldp_project_gui;

/**
 *
 * @author vasco
 */
public class JFrameMenuListarPerguntas extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMenuListarPerguntas
     */
    public JFrameMenuListarPerguntas() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanelListarPerguntas1 = new javax.swing.JPanel();
        botaoAddPergunta = new javax.swing.JButton();
        JLabelAddPergunta = new javax.swing.JLabel();
        jComboBoxTemaLista = new javax.swing.JComboBox<>();
        jComboBoxCadeiraLista = new javax.swing.JComboBox<>();
        jComboBoxDificuldadeLista = new javax.swing.JComboBox<>();
        jComboBoxTipoPerguntaLista = new javax.swing.JComboBox<>();
        jLabelCadeiraLista = new javax.swing.JLabel();
        jLabelTemaLista = new javax.swing.JLabel();
        jLabelTipoPerguntaLista = new javax.swing.JLabel();
        jLabelDificuldadeLista = new javax.swing.JLabel();
        tituloListaDePerguntas = new javax.swing.JLabel();
        botaoMenuPrincipal_ListarPerguntas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        botaoRemoverTema = new javax.swing.JButton();
        botaoRemoverUc = new javax.swing.JButton();
        JLabelRemoverTema = new javax.swing.JLabel();
        JLabelRemoverUC = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelListarPerguntas1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        botaoAddPergunta.setText("+");
        botaoAddPergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddPerguntaActionPerformed(evt);
            }
        });

        JLabelAddPergunta.setText("Pergunta");

        jComboBoxTemaLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTemaLista.setSelectedIndex(-1);

        jComboBoxCadeiraLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCadeiraLista.setSelectedIndex(-1);

        jComboBoxDificuldadeLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Muito Fácil", "Fácil", "Médio", "Difícil", "Muito Difícil" }));
        jComboBoxDificuldadeLista.setSelectedIndex(-1);

        jComboBoxTipoPerguntaLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha Múltipla", "Desenvolvimento", "Curta", "Calculada", "Correspondência de Colunas" }));
        jComboBoxTipoPerguntaLista.setSelectedIndex(-1);
        jComboBoxTipoPerguntaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoPerguntaListaActionPerformed(evt);
            }
        });

        jLabelCadeiraLista.setText("Cadeira");

        jLabelTemaLista.setText("Tema");

        jLabelTipoPerguntaLista.setText("Tipo de pergunta");

        jLabelDificuldadeLista.setText("Dificuldade");

        javax.swing.GroupLayout jPanelListarPerguntas1Layout = new javax.swing.GroupLayout(jPanelListarPerguntas1);
        jPanelListarPerguntas1.setLayout(jPanelListarPerguntas1Layout);
        jPanelListarPerguntas1Layout.setHorizontalGroup(
            jPanelListarPerguntas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarPerguntas1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListarPerguntas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDificuldadeLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTipoPerguntaLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTemaLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCadeiraLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelListarPerguntas1Layout.createSequentialGroup()
                        .addGroup(jPanelListarPerguntas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelListarPerguntas1Layout.createSequentialGroup()
                                .addComponent(botaoAddPergunta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JLabelAddPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxTemaLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCadeiraLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxDificuldadeLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jComboBoxTipoPerguntaLista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelListarPerguntas1Layout.setVerticalGroup(
            jPanelListarPerguntas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListarPerguntas1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelCadeiraLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCadeiraLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTemaLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTemaLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDificuldadeLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxDificuldadeLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTipoPerguntaLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTipoPerguntaLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanelListarPerguntas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAddPergunta)
                    .addComponent(JLabelAddPergunta))
                .addGap(71, 71, 71))
        );

        tituloListaDePerguntas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloListaDePerguntas.setText("Lista de Perguntas");

        botaoMenuPrincipal_ListarPerguntas.setText("Menu Principal");
        botaoMenuPrincipal_ListarPerguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuPrincipal_ListarPerguntasActionPerformed(evt);
            }
        });

        botaoRemoverTema.setText("*");
        botaoRemoverTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverTemaActionPerformed(evt);
            }
        });

        botaoRemoverUc.setText("*");
        botaoRemoverUc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverUcActionPerformed(evt);
            }
        });

        JLabelRemoverTema.setText("Temas");

        JLabelRemoverUC.setText("Unidades Curriculares");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(botaoMenuPrincipal_ListarPerguntas)
                .addGap(277, 277, 277)
                .addComponent(tituloListaDePerguntas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(462, 462, 462))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelListarPerguntas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoRemoverTema)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLabelRemoverTema, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoRemoverUc)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLabelRemoverUC)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloListaDePerguntas, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(botaoMenuPrincipal_ListarPerguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelListarPerguntas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoRemoverTema)
                    .addComponent(botaoRemoverUc)
                    .addComponent(JLabelRemoverTema)
                    .addComponent(JLabelRemoverUC))
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMenuPrincipal_ListarPerguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuPrincipal_ListarPerguntasActionPerformed
        // TODO add your handling code here:
        
        JFrameMenuPrincipal jf1 = new JFrameMenuPrincipal();
        jf1.show(); //display JFrameMenuQuizManual
        
        dispose(); //fechar o frame atual
    }//GEN-LAST:event_botaoMenuPrincipal_ListarPerguntasActionPerformed

    private void botaoAddPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddPerguntaActionPerformed
        JFrameAddPergunta jf4 = new JFrameAddPergunta();
        jf4.show(); //display JFrameMenuQuizManual        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAddPerguntaActionPerformed

    private void botaoRemoverTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverTemaActionPerformed
        JFrameListaTema jf5 = new JFrameListaTema();
        jf5.show(); //display JFrameMenuQuizManual
        
    }//GEN-LAST:event_botaoRemoverTemaActionPerformed

    private void botaoRemoverUcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverUcActionPerformed
        // TODO add your handling code here:
        JFrameListaUC jf6 = new JFrameListaUC();
        jf6.show(); //display JFrameMenuQuizManual
    }//GEN-LAST:event_botaoRemoverUcActionPerformed

    private void jComboBoxTipoPerguntaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoPerguntaListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoPerguntaListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuListarPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuListarPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuListarPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuListarPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenuListarPerguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelAddPergunta;
    private javax.swing.JLabel JLabelRemoverTema;
    private javax.swing.JLabel JLabelRemoverUC;
    private javax.swing.JButton botaoAddPergunta;
    private javax.swing.JButton botaoMenuPrincipal_ListarPerguntas;
    private javax.swing.JButton botaoRemoverTema;
    private javax.swing.JButton botaoRemoverUc;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBoxCadeiraLista;
    private javax.swing.JComboBox<String> jComboBoxDificuldadeLista;
    private javax.swing.JComboBox<String> jComboBoxTemaLista;
    private javax.swing.JComboBox<String> jComboBoxTipoPerguntaLista;
    private javax.swing.JLabel jLabelCadeiraLista;
    private javax.swing.JLabel jLabelDificuldadeLista;
    private javax.swing.JLabel jLabelTemaLista;
    private javax.swing.JLabel jLabelTipoPerguntaLista;
    private javax.swing.JPanel jPanelListarPerguntas1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tituloListaDePerguntas;
    // End of variables declaration//GEN-END:variables
}
