/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ldp_project_gui;

/**
 *
 * @author vasco
 */
public class RespostaEscolhaMultipla extends javax.swing.JFrame {

    /**
     * Creates new form EscolhaMultipla
     */
    public RespostaEscolhaMultipla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNomePerguntaEM = new javax.swing.JTextField();
        jTextFieldPerguntaPerguntaEM = new javax.swing.JTextField();
        botaoAddOpcaoPerguntaEM = new javax.swing.JToggleButton();
        jLabelAddOpcaoPerguntaEM = new javax.swing.JLabel();
        botaoSubmeterPerguntaEM = new javax.swing.JButton();
        jCheckBoxResposta2PerguntaEM = new javax.swing.JCheckBox();
        jCheckBoxResposta4PerguntaEM = new javax.swing.JCheckBox();
        jCheckBoxResposta3PerguntaEM = new javax.swing.JCheckBox();
        jCheckBoxResposta1PerguntaEM = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldNomePerguntaEM.setText("Título");

        jTextFieldPerguntaPerguntaEM.setText("Pergunta");

        botaoAddOpcaoPerguntaEM.setText("+");

        jLabelAddOpcaoPerguntaEM.setText("Opção");

        botaoSubmeterPerguntaEM.setText("Submeter");

        jCheckBoxResposta2PerguntaEM.setText("Resposta 2");
        jCheckBoxResposta2PerguntaEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxResposta2PerguntaEMActionPerformed(evt);
            }
        });

        jCheckBoxResposta4PerguntaEM.setText("Resposta 4");

        jCheckBoxResposta3PerguntaEM.setText("Resposta 3");

        jCheckBoxResposta1PerguntaEM.setText("Resposta 1");
        jCheckBoxResposta1PerguntaEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxResposta1PerguntaEMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldPerguntaPerguntaEM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomePerguntaEM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxResposta2PerguntaEM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxResposta3PerguntaEM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxResposta4PerguntaEM, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxResposta1PerguntaEM, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botaoAddOpcaoPerguntaEM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAddOpcaoPerguntaEM, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addComponent(botaoSubmeterPerguntaEM, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTextFieldNomePerguntaEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldPerguntaPerguntaEM, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAddOpcaoPerguntaEM)
                    .addComponent(jLabelAddOpcaoPerguntaEM)
                    .addComponent(jCheckBoxResposta1PerguntaEM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxResposta2PerguntaEM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxResposta3PerguntaEM)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSubmeterPerguntaEM)
                    .addComponent(jCheckBoxResposta4PerguntaEM))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxResposta2PerguntaEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxResposta2PerguntaEMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxResposta2PerguntaEMActionPerformed

    private void jCheckBoxResposta1PerguntaEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxResposta1PerguntaEMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxResposta1PerguntaEMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RespostaEscolhaMultipla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RespostaEscolhaMultipla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RespostaEscolhaMultipla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RespostaEscolhaMultipla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RespostaEscolhaMultipla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botaoAddOpcaoPerguntaEM;
    private javax.swing.JButton botaoSubmeterPerguntaEM;
    private javax.swing.JCheckBox jCheckBoxResposta1PerguntaEM;
    private javax.swing.JCheckBox jCheckBoxResposta2PerguntaEM;
    private javax.swing.JCheckBox jCheckBoxResposta3PerguntaEM;
    private javax.swing.JCheckBox jCheckBoxResposta4PerguntaEM;
    private javax.swing.JLabel jLabelAddOpcaoPerguntaEM;
    private javax.swing.JTextField jTextFieldNomePerguntaEM;
    private javax.swing.JTextField jTextFieldPerguntaPerguntaEM;
    // End of variables declaration//GEN-END:variables
}
