/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.ListarPerguntas;

import Controller.listagem_de_perguntas;
import Views.AddQuestion.*;
import Views.PopupErros.*;

import java.sql.SQLException;

/**
 *
 * @author vasco
 */
public class JFramePopupAdicionarUC extends javax.swing.JFrame {

    /**
     * Creates new form JFramePopupAdicionarUC
     */
    public JFramePopupAdicionarUC() {
        initComponents();
        setDefaultCloseOperation(JFrameAddPergunta.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloUC = new javax.swing.JLabel();
        jLabelInserirUC = new javax.swing.JLabel();
        jTextFieldInserirUC = new javax.swing.JTextField();
        botaoAdicionarUC = new javax.swing.JButton();
        botaoAdicionarTema1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTituloUC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTituloUC.setText("Adicionar Unidade Curricular");

        jLabelInserirUC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelInserirUC.setText("Inserir Unidade Curricular:");

        botaoAdicionarUC.setText("Adicionar");
        botaoAdicionarUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String value = null;
                if(!jTextFieldInserirUC.getText().isEmpty()){
                    try {
                        value = listagem_de_perguntas.isthereUCName(jTextFieldInserirUC.getText());
                        System.out.println(value);
                    } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }
                    if(value.equals("0")){

                        try {
                            listagem_de_perguntas.addUC(jTextFieldInserirUC.getText());
                        } catch (SQLException e) {
                            throw new RuntimeException(e);
                        }
                        JFrameListaUC jf1 = null;
                        try {
                            jf1 = new JFrameListaUC();
                        } catch (SQLException e) {
                            throw new RuntimeException(e);
                        }
                        jf1.show(); //display JFrameMenuQuizManual
                        dispose();
                    } else{
                        JFramePopupUCExistente jf1 = new JFramePopupUCExistente();
                        jf1.show();
                    }
                }
            }
        });

        botaoAdicionarTema1.setText("Back");
        botaoAdicionarTema1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    botaoAdicionarTema1ActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabelTituloUC))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoAdicionarUC)
                            .addComponent(jLabelInserirUC))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldInserirUC, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(botaoAdicionarTema1)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelTituloUC)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInserirUC)
                    .addComponent(jTextFieldInserirUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAdicionarUC)
                    .addComponent(botaoAdicionarTema1))
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAdicionarTema1ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_botaoAdicionarTema1ActionPerformed
        // TODO add your handling code here:
        
        JFrameListaUC jf1 = new JFrameListaUC();
        jf1.show(); //display JFrameMenuListarPerguntas

        dispose(); //fechar o frame atual
    }//GEN-LAST:event_botaoAdicionarTema1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePopupAdicionarUC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePopupAdicionarUC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePopupAdicionarUC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePopupAdicionarUC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePopupAdicionarUC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionarTema1;
    private javax.swing.JButton botaoAdicionarUC;
    private javax.swing.JLabel jLabelInserirUC;
    private javax.swing.JLabel jLabelTituloUC;
    private javax.swing.JTextField jTextFieldInserirUC;
    // End of variables declaration//GEN-END:variables
}
