/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.ListarPerguntas;

import Controller.listagem_de_perguntas;

import Views.AddQuestion.*;
import Views.PopupErros.*;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.List;

/**
 *
 * @author vasco
 */
public class JFramePopupAdicionarTema extends JFrame {

    /**
     * Creates new form JFramePopupAdicionarTema
     */
    public JFramePopupAdicionarTema() throws SQLException {
        initComponents();
        setDefaultCloseOperation(JFrameAddPergunta.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws SQLException {

        jLabelTituloTema = new JLabel();
        jLabelInserirTema = new JLabel();
        jTextFieldInserirTema = new JTextField();
        botaoAdicionarTema = new JButton();
        botaoAdicionarTema1 = new JButton();
        jLabel1 = new JLabel();
        jComboBox1 = new JComboBox<>();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabelTituloTema.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTituloTema.setText("Adicionar Tema");

        jLabelInserirTema.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelInserirTema.setText("Inserir Tema:");

        botaoAdicionarTema.setText("Adicionar");
        botaoAdicionarTema.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                String value;
                try {
                     value = listagem_de_perguntas.isthereTopicName(jTextFieldInserirTema.getText(), jComboBox1.getSelectedItem().toString());
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
                if(value.equals("0")){

                    try {
                        listagem_de_perguntas.addTopic(jTextFieldInserirTema.getText(), jComboBox1.getSelectedItem().toString());
                    } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }
                    JFrameListaTema jf1 = null;
                    try {
                        jf1 = new JFrameListaTema();
                    } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }
                    jf1.show(); //display JFrameMenuQuizManual
                    dispose();
                } else{
                    JFramePopupTemaExistente jf1 = new JFramePopupTemaExistente();
                    jf1.show();
                }
                }

            });

        botaoAdicionarTema1.setText("Back");
        botaoAdicionarTema1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                try {
                    botaoAdicionarTema1ActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Unidade Curricular a que o tema vai pertencer:");

        jComboBox1.setModel(new DefaultComboBoxModel<>(new String[] {}));

        List<String> values = listagem_de_perguntas.getSubjects();
        for(int i = 0; i< values.size(); i++) {
            jComboBox1.addItem(values.get(i));
        }

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTituloTema)
                .addGap(171, 171, 171))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(botaoAdicionarTema)
                        .addGap(80, 80, 80)
                        .addComponent(botaoAdicionarTema1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelInserirTema)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldInserirTema, GroupLayout.PREFERRED_SIZE, 315, GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, 175, GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelTituloTema)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInserirTema)
                    .addComponent(jTextFieldInserirTema, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAdicionarTema)
                    .addComponent(botaoAdicionarTema1)
                )

                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAdicionarTema1ActionPerformed(ActionEvent evt) throws SQLException {//GEN-FIRST:event_botaoAdicionarTema1ActionPerformed
        // TODO add your handling code here:
        JFrameListaTema jf1 = new JFrameListaTema();
        jf1.show(); //display JFrameMenuListarPerguntas

        dispose(); //fechar o frame atual

    }//GEN-LAST:event_botaoAdicionarTema1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePopupAdicionarTema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePopupAdicionarTema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePopupAdicionarTema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePopupAdicionarTema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFramePopupAdicionarTema().setVisible(true);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton botaoAdicionarTema;
    private JButton botaoAdicionarTema1;
    private JComboBox<String> jComboBox1;
    private JLabel jLabel1;
    private JLabel jLabelInserirTema;
    private JLabel jLabelTituloTema;
    private JTextField jTextFieldInserirTema;
    private JButton botaoBack;
    // End of variables declaration//GEN-END:variables
}
