/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.UIManager;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;


/**
 *
 * @author vasco
 */
public class JFrameMenuPrincipal extends javax.swing.JFrame {

    

    /**
     * Creates new form JFrameMenuPrincipal
     */
    public JFrameMenuPrincipal() {
        
        
   
        initComponents();

        labelNomesIdentificacao.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            JFrameCreditos jf2 = new JFrameCreditos();
            jf2.show(); //display JFrameMenuQuizManual
        
        dispose(); //fechar o frame atual    
        }
    });
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloMenuPrincipal = new javax.swing.JLabel();
        botaoQuizManual = new javax.swing.JButton();
        botaoQuizAutomatico = new javax.swing.JButton();
        botaoListarPerguntas = new javax.swing.JButton();
        labelNomesIdentificacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloMenuPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tituloMenuPrincipal.setText("Ferramenta de Geração de Testes e Provas");

        botaoQuizManual.setText("Gerar Quiz Manual");
        botaoQuizManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    botaoQuizManualActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        botaoQuizAutomatico.setText("Gerar Quiz Automático");
        botaoQuizAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    botaoQuizAutomaticoActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        botaoListarPerguntas.setText("Lista de Perguntas");
        botaoListarPerguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    botaoListarPerguntasActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        labelNomesIdentificacao.setText("Créditos e Copyright");
        labelNomesIdentificacao.setForeground(Color.BLUE);


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tituloMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoQuizManual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoQuizAutomatico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(botaoListarPerguntas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNomesIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(tituloMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoQuizManual, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoQuizAutomatico, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                    .addComponent(botaoListarPerguntas, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addComponent(labelNomesIdentificacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoQuizManualActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_botaoQuizManualActionPerformed
        // Open JFrame Menu Gerar Quiz Manual
        JFrameMenuQuizManual jf2 = new JFrameMenuQuizManual();
        jf2.show(); //display JFrameMenuQuizManual
        
        dispose(); //fechar o frame atual
    }//GEN-LAST:event_botaoQuizManualActionPerformed

    private void botaoListarPerguntasActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_botaoListarPerguntasActionPerformed
        // TODO add your handling code here:
                // Open JFrame Menu Gerar Quiz Manual
        JFrameMenuListarPerguntas jf3 = new JFrameMenuListarPerguntas();
        jf3.show(); //display JFrameMenuQuizManual
        
        dispose(); //fechar o frame atual
    }//GEN-LAST:event_botaoListarPerguntasActionPerformed

    private void botaoQuizAutomaticoActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_botaoQuizAutomaticoActionPerformed
        JFrameMenuQuizAutomatico jf3 = new JFrameMenuQuizAutomatico();
        jf3.show(); //display JFrameMenuQuizManual
        dispose(); //fechar o frame atual        // TODO add your handling code here:
    }//GEN-LAST:event_botaoQuizAutomaticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println(info);
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoListarPerguntas;
    private javax.swing.JButton botaoQuizAutomatico;
    private javax.swing.JButton botaoQuizManual;
    private javax.swing.JLabel labelNomesIdentificacao;
    private javax.swing.JLabel tituloMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
