/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author vasco
 */
public class JFrameMenuQuizManual extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMenuQuizManual
     */
    public JFrameMenuQuizManual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoMenuPrincipalQuizManual = new javax.swing.JButton();
        jPanelQuizManual1 = new javax.swing.JPanel();
        botaoRemoverUltimaPergunta = new javax.swing.JButton();
        botaoAddPerguntaQuizManual = new javax.swing.JButton();
        jLabelAddPerguntaQuizManual = new javax.swing.JLabel();
        jLabelRemovePerguntaQuizManual = new javax.swing.JLabel();
        NPerguntas = new javax.swing.JTextField();
        botaoSubmitNPerguntas = new javax.swing.JButton();
        jTextFieldNomeQuizManual = new javax.swing.JTextField();
        tituloQuizManual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoMenuPrincipalQuizManual.setText("Menu Principal");
        botaoMenuPrincipalQuizManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuPrincipalQuizManualActionPerformed(evt);
            }
        });

        jPanelQuizManual1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        botaoRemoverUltimaPergunta.setText("-");

        botaoAddPerguntaQuizManual.setText("+");

        jLabelAddPerguntaQuizManual.setText("Adicionar Pergunta");

        jLabelRemovePerguntaQuizManual.setText("Remover Última Pergunta");

        NPerguntas.setText("Nº Perguntas");

        botaoSubmitNPerguntas.setText("Submit");

        javax.swing.GroupLayout jPanelQuizManual1Layout = new javax.swing.GroupLayout(jPanelQuizManual1);
        jPanelQuizManual1.setLayout(jPanelQuizManual1Layout);
        jPanelQuizManual1Layout.setHorizontalGroup(
            jPanelQuizManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuizManual1Layout.createSequentialGroup()
                .addGroup(jPanelQuizManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuizManual1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(botaoRemoverUltimaPergunta, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRemovePerguntaQuizManual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelQuizManual1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanelQuizManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelQuizManual1Layout.createSequentialGroup()
                                .addComponent(botaoAddPerguntaQuizManual, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAddPerguntaQuizManual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(35, 35, 35))
                            .addGroup(jPanelQuizManual1Layout.createSequentialGroup()
                                .addComponent(NPerguntas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoSubmitNPerguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanelQuizManual1Layout.setVerticalGroup(
            jPanelQuizManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQuizManual1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelQuizManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuizManual1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(NPerguntas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoSubmitNPerguntas))
                .addGap(18, 18, 18)
                .addGroup(jPanelQuizManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuizManual1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabelAddPerguntaQuizManual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(botaoAddPerguntaQuizManual))
                .addGap(10, 10, 10)
                .addGroup(jPanelQuizManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuizManual1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabelRemovePerguntaQuizManual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(botaoRemoverUltimaPergunta))
                .addGap(33, 33, 33))
        );

        jTextFieldNomeQuizManual.setText("Nome do Quiz");
        jTextFieldNomeQuizManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeQuizManualActionPerformed(evt);
            }
        });

        tituloQuizManual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloQuizManual.setText("Gerar Quiz Manual");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNomeQuizManual)
                    .addComponent(botaoMenuPrincipalQuizManual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(277, 277, 277)
                .addComponent(tituloQuizManual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(440, 440, 440))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanelQuizManual1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(tituloQuizManual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(botaoMenuPrincipalQuizManual, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNomeQuizManual, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(57, 57, 57)
                .addComponent(jPanelQuizManual1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMenuPrincipalQuizManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuPrincipalQuizManualActionPerformed
       JFrameMenuPrincipal jf1 = new JFrameMenuPrincipal();
        jf1.show(); //display JFrameMenuQuizManual
        
        dispose(); //fechar o frame atual        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMenuPrincipalQuizManualActionPerformed

    private void jTextFieldNomeQuizManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeQuizManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeQuizManualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuQuizManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuQuizManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuQuizManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuQuizManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenuQuizManual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NPerguntas;
    private javax.swing.JButton botaoAddPerguntaQuizManual;
    private javax.swing.JButton botaoMenuPrincipalQuizManual;
    private javax.swing.JButton botaoRemoverUltimaPergunta;
    private javax.swing.JButton botaoSubmitNPerguntas;
    private javax.swing.JLabel jLabelAddPerguntaQuizManual;
    private javax.swing.JLabel jLabelRemovePerguntaQuizManual;
    private javax.swing.JPanel jPanelQuizManual1;
    private javax.swing.JTextField jTextFieldNomeQuizManual;
    private javax.swing.JLabel tituloQuizManual;
    // End of variables declaration//GEN-END:variables
}
