/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Controller.listagem_de_perguntas;
import com.sun.source.doctree.StartElementTree;

import java.sql.SQLException;

/**
 *
 * @author vasco
 */
public class RespostaEscolhaMultipla extends javax.swing.JFrame {

    /**
     * Creates new form EscolhaMultipla
     */
    public RespostaEscolhaMultipla(String subject, String topic) {

        initComponents(subject, topic);
        setDefaultCloseOperation(RespostaEscolhaMultipla.DISPOSE_ON_CLOSE);
    }

    public RespostaEscolhaMultipla() {

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String subject, String topic) {

        botaoSubmeterPerguntaEM = new javax.swing.JButton();
        jCheckBoxResposta1PerguntaEM = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jCheckBoxResposta1PerguntaEM1 = new javax.swing.JCheckBox();
        jTextField3 = new javax.swing.JTextField();
        jCheckBoxResposta1PerguntaEM2 = new javax.swing.JCheckBox();
        jTextField5 = new javax.swing.JTextField();
        jCheckBoxResposta1PerguntaEM4 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoSubmeterPerguntaEM.setText("Submeter");
        botaoSubmeterPerguntaEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(!(jTextArea1.getText().equals("Pergunta") || jTextArea1.getText().equals("") || jTextField1.getText().equals("") || jTextField2.getText().equals("") || jTextField3.getText().equals("") || jTextField5.getText().equals(""))){
                    String topicid = null;
                    try {
                        topicid = listagem_de_perguntas.getTopicIdwithSubjectandtopic(subject, topic);
                    } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }

                    int selectedCount = 0;
                    if(jCheckBoxResposta1PerguntaEM.isSelected()){
                        selectedCount++;
                    }
                    if(jCheckBoxResposta1PerguntaEM1.isSelected()){
                        selectedCount++;
                    }
                    if(jCheckBoxResposta1PerguntaEM2.isSelected()){
                        selectedCount++;
                    }
                    if(jCheckBoxResposta1PerguntaEM4.isSelected()){
                        selectedCount++;
                    }

                    if(selectedCount == 1){
                        String query = String.format("INSERT INTO QUESTION (description, type, topicid) VALUES ('%s', 'Escolha múltipla', '%s');", jTextArea1.getText().toString(), topicid);
                        String id;

                        try {
                            listagem_de_perguntas.addQuestion(query);
                        } catch (SQLException e) {
                            throw new RuntimeException(e);
                        }

                        try {
                            id = listagem_de_perguntas.maxid();
                        } catch (SQLException e) {
                            throw new RuntimeException(e);
                        }

                        try {
                            listagem_de_perguntas.addQuestion(String.format("INSERT INTO MultipleChoice VALUES ('%s', %b, false, %s);",jTextField1.getText(), jCheckBoxResposta1PerguntaEM.isSelected(), id));
                        } catch (SQLException e) {
                            throw new RuntimeException(e);
                        }

                        try {
                            listagem_de_perguntas.addQuestion(String.format("INSERT INTO MultipleChoice VALUES ('%s', %b, false, %s);",jTextField2.getText(), jCheckBoxResposta1PerguntaEM1.isSelected(), id));
                        } catch (SQLException e) {
                            throw new RuntimeException(e);
                        }

                        try {
                            listagem_de_perguntas.addQuestion(String.format("INSERT INTO MultipleChoice VALUES ('%s', %b, false, %s);",jTextField3.getText(), jCheckBoxResposta1PerguntaEM2.isSelected(), id));
                        } catch (SQLException e) {
                            throw new RuntimeException(e);
                        }

                        try {
                            listagem_de_perguntas.addQuestion(String.format("INSERT INTO MultipleChoice VALUES ('%s', %b, false, %s);",jTextField5.getText(), jCheckBoxResposta1PerguntaEM4.isSelected(), id));
                        } catch (SQLException e) {
                            throw new RuntimeException(e);
                        }
                        dispose();
                    } else if(selectedCount > 1){
                        String query = String.format("INSERT INTO QUESTION (description, type, topicid) VALUES ('%s', 'Múltipla escolha', '%s');", jTextArea1.getText().toString(), topicid);
                        String id;

                        try {
                            listagem_de_perguntas.addQuestion(query);
                        } catch (SQLException e) {
                            throw new RuntimeException(e);
                        }

                        try {
                            id = listagem_de_perguntas.maxid();
                        } catch (SQLException e) {
                            throw new RuntimeException(e);
                        }

                        try {
                            listagem_de_perguntas.addQuestion(String.format("INSERT INTO MultipleChoice VALUES ('%s', %b, true, %s);",jTextField1.getText(), jCheckBoxResposta1PerguntaEM.isSelected(), id));
                        } catch (SQLException e) {
                            throw new RuntimeException(e);
                        }

                        try {
                            listagem_de_perguntas.addQuestion(String.format("INSERT INTO MultipleChoice VALUES ('%s', %b, true, %s);",jTextField2.getText(), jCheckBoxResposta1PerguntaEM1.isSelected(), id));
                        } catch (SQLException e) {
                            throw new RuntimeException(e);
                        }

                        try {
                            listagem_de_perguntas.addQuestion(String.format("INSERT INTO MultipleChoice VALUES ('%s', %b, true, %s);",jTextField3.getText(), jCheckBoxResposta1PerguntaEM2.isSelected(), id));
                        } catch (SQLException e) {
                            throw new RuntimeException(e);
                        }

                        try {
                            listagem_de_perguntas.addQuestion(String.format("INSERT INTO MultipleChoice VALUES ('%s', %b, true, %s);",jTextField5.getText(), jCheckBoxResposta1PerguntaEM4.isSelected(), id));
                        } catch (SQLException e) {
                            throw new RuntimeException(e);
                        }
                        dispose();
                    }

                }

            }
        });

        jCheckBoxResposta1PerguntaEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxResposta1PerguntaEMActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Pergunta");
        jScrollPane1.setViewportView(jTextArea1);

        jCheckBoxResposta1PerguntaEM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxResposta1PerguntaEM1ActionPerformed(evt);
            }
        });

        jCheckBoxResposta1PerguntaEM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxResposta1PerguntaEM2ActionPerformed(evt);
            }
        });

        jCheckBoxResposta1PerguntaEM4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxResposta1PerguntaEM4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxResposta1PerguntaEM4)
                                .addGap(7, 7, 7)
                                .addComponent(jTextField5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCheckBoxResposta1PerguntaEM1)
                                .addGap(7, 7, 7)
                                .addComponent(jTextField2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCheckBoxResposta1PerguntaEM)
                                .addGap(7, 7, 7)
                                .addComponent(jTextField1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCheckBoxResposta1PerguntaEM2)
                                .addGap(7, 7, 7)
                                .addComponent(jTextField3)))
                        .addGap(235, 235, 235)
                        .addComponent(botaoSubmeterPerguntaEM, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jCheckBoxResposta1PerguntaEM)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jCheckBoxResposta1PerguntaEM1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jCheckBoxResposta1PerguntaEM2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jCheckBoxResposta1PerguntaEM4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoSubmeterPerguntaEM)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxResposta1PerguntaEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxResposta1PerguntaEMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxResposta1PerguntaEMActionPerformed

    private void jCheckBoxResposta1PerguntaEM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxResposta1PerguntaEM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxResposta1PerguntaEM1ActionPerformed

    private void jCheckBoxResposta1PerguntaEM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxResposta1PerguntaEM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxResposta1PerguntaEM2ActionPerformed

    private void jCheckBoxResposta1PerguntaEM4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxResposta1PerguntaEM4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxResposta1PerguntaEM4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RespostaEscolhaMultipla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RespostaEscolhaMultipla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RespostaEscolhaMultipla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RespostaEscolhaMultipla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RespostaEscolhaMultipla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSubmeterPerguntaEM;
    private javax.swing.JCheckBox jCheckBoxResposta1PerguntaEM;
    private javax.swing.JCheckBox jCheckBoxResposta1PerguntaEM1;
    private javax.swing.JCheckBox jCheckBoxResposta1PerguntaEM2;
    private javax.swing.JCheckBox jCheckBoxResposta1PerguntaEM4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
